### PR TITLE
added default item image for when no image is selected for item publish

### PR DESCRIPTION
**Pull request by hugginsc10**
# Description

fix for  #2 
Screen Shot 2022-07-18 at 7 24 21 PM

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @hugginsc10, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by hugginsc10 — COMMENTED** [review]
reviewed changes

**Review by hugginsc10 — COMMENTED** [review]
reviewed

**Pull request closed without merging**
